version: '3.4'

services:
  postgresql:
    image: docker.io/library/postgres:12.13-alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: emu-oncall
    volumes:
      - ./.docker/postgre:/docker-entrypoint-initdb.d
    networks:
      - ironmaiden
    ports:
      - '15432:5432'

networks:
  emuoncall:
    driver: bridge
