emu-oncall:
  debug: true
  app:
    port: ":10080"
    hostname: "localhost"
    env: "prod"
    log_level: "debug"

grafana: # if this is set, service will load users from Grafana
  url: "https://grafana.biz-systems.ru/"
  import_users: true
  auth:
    user: "e.bogdanov"
    password: "testpassword"

  oncall: # if this is set, service will track schedules or notify users
    schedule:
      url: ""
      enable: true
      auth:
        username: "test"
        password: "test"
    incident_details:
      enable: true
      source: "local" # local vs remote
      url: "http://localhost:8080/"

db:
  addr: "localhost"
  user: "emu-oncall"
  password: "P2wd_1126cf74fea188835dab13"
  dbname: "emu-oncall"
  driver: "postgres"

notify:
  plugin: "notify"
  config: "config/notify.yaml"