voip:
  url: "http://voip-tts.biz-systems.ru/api/v1/call_to"
  ack_mode: "CONFIRM"
push:
  title: "=== Grafana On-Call ==="
  url: "http://push-service.biz-systems.ru/api/v2/client/send"
db:
  addr: "postgresdb-test.biz-systems.ru:5432"
  user: "emu-oncall"
  password: "P2wd_1126cf74fea188835dab13"
  dbname: "emu-oncall"
  driver: "postgres"
